name: datalib
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.8.30=h56e8100_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py312hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=h5da7b33_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.27.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312haa95532_0
  - krb5=1.21.3=hdf4eb48_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.2=h2466b09_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py312haa95532_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=5.9.0=py312h2bbff1b_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.12.4=h14ffc60_1
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - pywin32=305=py312h2bbff1b_0
  - pyzmq=25.1.2=py312hd77b12b_0
  - setuptools=72.1.0=py312haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.1=py312h827c3e9_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.40=h2eaa2aa_0
  - vc14_runtime=14.40.33810=hcc2c482_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zeromq=4.3.5=he1f189c_5
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - ckanapi==4.8
      - docopt==0.6.2
      - idna==3.8
      - python-slugify==8.0.4
      - requests==2.32.3
      - simplejson==3.19.3
      - text-unidecode==1.3
      - urllib3==2.2.2
prefix: C:\Users\alessandra.gherardel\AppData\Local\miniconda3\envs\datalib
